### ISSUE TITLE
Actions build pipeline

### ISSUE THREAD

**Issue by StephenMiracle** [StephenMiracle/frankenwp#10]
Need a build pipeline using github actions to deploy into Docker hub.

**Comment by scheibling** [comment]
@StephenMiracle You could just create a regular account with the name, and then convert it to an organization some time in the future if need be

**Comment by StephenMiracle** [comment]
Just saw comment @scheibling .  That is similar to what I did. I already had a wpeverywhere account and read article that you can switch to organization. 

Here's the new org. The pipelines now build and deploy to there. 
https://hub.docker.com/r/wpeverywhere/frankenwp
