### ISSUE TITLE
Sidekick caches responses > 299

### ISSUE THREAD

**Issue by PascaleBeier** [StephenMiracle/frankenwp#12]
I think the expected behaviour would be if sidekick would bypass anything that is not in the 2XX range

**Comment by StephenMiracle** [comment]
Didn't mean to resolve yet.

**Comment by StephenMiracle** [comment]
Hey @PascaleBeier , this has been integrated into the beta-1.0.0 image if you want to do a pull and test.

Environment variable:
CACHE_RESPONSE_CODES=2XX,404,405

Pull request here: https://github.com/StephenMiracle/frankenwp/pull/15

Feel free to review and give feedback.
