### ISSUE TITLE
Wrong URLs in README

### ISSUE THREAD

**Issue by ben221199** [StephenMiracle/frankenwp#19]
This leads us to a login page for Docker Hub. I think you meant `https://hub.docker.com/r/stephenmiracle/frankenwp`:
https://github.com/StephenMiracle/frankenwp/blob/1662b606c66ec966a96d8f6383fd766b0fb91ae0/README.md?plain=1#L7

---

This URL has a trailing `,` that makes the URL give a 404:
https://github.com/StephenMiracle/frankenwp/blob/1662b606c66ec966a96d8f6383fd766b0fb91ae0/README.md?plain=1#L8

**Comment by StephenMiracle** [comment]
Got it. Thanks for the catch. Will update.
