### ISSUE TITLE
Does not run on Rocky Linux 9 AMD64

### ISSUE THREAD

**Issue by StephenMiracle** [StephenMiracle/frankenwp#3]
Getting build errors for WordPress on Rocky Linux 9 AMD64

Original Ticket found here.

https://github.com/StephenMiracle/wordpress-docker-frankenphp/issues/3

**Comment by jerome-pilotin** [comment]
Hi Stephen

Thank you for taking a look at it. I've spent a bit of my morning spinning a Debian 12 instance to see if that works there, to no avail: same error.

I've tried also on the RockyLinux instance to build the caddy executable but it failed too

**Comment by jerome-pilotin** [comment]
I have pulled your changes from yesterday and have been able to build the image locally, and it seems to be working without issues! I'll report back with more info. Thanks a lot for you hard work, and for sharing it!
