### ISSUE TITLE
Some cached pages have encoding or compression issues

### ISSUE THREAD

**Issue by jerome-pilotin** [StephenMiracle/frankenwp#4]
I've been informed that some pages seem to be cached with either wrong encoding, or more probably compression algorithm, causing those pages to appear like so on subsequent visits:

![image](https://github.com/StephenMiracle/frankenwp/assets/121434615/5db9bf91-785d-4cbe-8b3d-929fbc4cce46)

I have had to completely bypass the cache for the time being because it started to impact our SEO.

Can I provide you with more information, maybe files, so that you can track down the issue?

**Comment by StephenMiracle** [comment]
Hey @jerome-pilotin ! I missed this earlier. I had discovered the same last week and have already started updating.

I wasn't aware it was being used in a production setting outside of my use. 

I'll create a slack group so we and others can connect. I'll leave this issue open and notify when updated.

**Comment by StephenMiracle** [comment]
Hey @jerome-pilotin . Here's a slack chat if you want to join. It may work better to communicate through there: 
https://join.slack.com/t/thatmiracle/shared_invite/zt-2hxi2pz12-0Pnf8zwCB3zWZ9SJmC0Qtg

**Comment by StephenMiracle** [comment]
Hey @jerome-pilotin . I just pushed changes that should correct the caching issue. I'll run a build on it and send over the test docker image.

**Comment by StephenMiracle** [comment]
Here is the Docker tag that should have this caching issue fixed. 
stephenmiracle/frankenwp:beta-1.0.0
https://hub.docker.com/r/stephenmiracle/frankenwp/tags
